### ISSUE TITLE
Deepin下生成Tips出错

### ISSUE THREAD

**Issue by ghost** [kbengine/kbengine_docs#31]
感觉generate_python_tips.py 在Linux环境下没经过测试，文件路径的计算完全是按Windows的来。

在def findDocsFiles():里有 
     f = parent + "\\" + filename  
之后在def parseDocs(f):里有
     processName = f.split("\\")[1]  ，

 所以这里的"\\" 可能是故意用来做分割符的。在Linux下，这样的路径会导致 fd = open(t, "r", encoding="UTF-8")  这行打不开文件。

这里要做一下文本替换，我是这么做的
temp=f.replace("\\","/")
fd = open(temp, "r", encoding="UTF-8")
不要直接修改f，否则   processName = f.split("\\")[1]  ，这里分割又会出错。

然后在def writeTipsPy(processName, moduleName, datas):下
dirstr = "tips\\" + processName + "\\"
要改成
dirstr = "tips/" + processName + "/"

基本上就是斜杠导致的问题。

**Comment by ghost** [comment]
我操，双斜杠怎么会显示成单斜杠？上面的\\ 其实是\\\\。

**Comment by kbengine** [comment]
修正了
