### ISSUE TITLE
提示不完整

### ISSUE THREAD

**Issue by LogicCoder** [kbengine/kbengine_docs#32]
已经更新了最新版，生成的KBEngine.py还是接口非常不完整，另外没有KBEDebug.py

def文件中定义的属性没法自动识别

common中定义的工具类用import 没法感应

使用的vscode测试

**Comment by kebiao** [comment]
新版本直接在py中定义就有提示了

**Comment by kebiao** [comment]
KBEDebug.py不是引擎的，你自己找找在哪
